const ScreenNames = {
  Home: 'Home',
  AuthStack: 'AuthStack',
  Login: 'Login',
  Splash: 'Splash',
  BottomTabs: 'BottomTabs',
  Jobs: 'Applicants',
  Signup: 'Signup',
  CompleteProfile: 'CompleteProfile',
  Profile: 'Profile',
  OnBoarding: 'OnBoarding',
  SearchedJobs: 'SearchedJobs',
  JobDetails: 'JobDetails',
  CompanyProfile: 'CompanyProfile',
  ForEmployee: 'Employee',
  WelcomeEmployee: 'WelcomeEmployee',
  ComplateCompanyProfile: 'ComplateCompanyProfile',
  JobPost: 'JobPost',
  RegisterationSteps: 'RegisterationSteps',
  SearchCV: 'SearchCV',
  ComplateSearchedCv: 'ComplateSearchedCv',
  Applications: 'Apps',
  SaveScreen: 'Save',
  ExploreScreen: 'Explore',
  OTPScreen: 'OTPScreen',
  SignUpStepTwoCandidate: 'SignUpStepTwoCandidate',
  ForgetPassword: 'ForgetPassword',
  CVProfile: 'CVProfile',
};

export default Object.freeze(ScreenNames);
